### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by hallard** [marcobrianza/Lora_Node_1.3#1]
Dear Marco,

Looks like that this board is adapted from this [one](https://github.com/hallard/WeMos-Lora) I designed some time ago. This work has been done under the following license (it's mentionned into the read.me file) https://creativecommons.org/licenses/by-nc/4.0/ that says
```
Attribution — You must give appropriate credit, provide a link to the license, 
and indicate if changes were made. You may do so in any reasonable manner, 
but not in any way that suggests the licensor endorses you or your use.
```
It would have been fair to mention the original author/design and add licensing mode in your awesome new version.

Regards,

**Comment by marcobrianza** [comment]
Hello @hallard ,
I just see this issue today.
The credit to your project and link is in the first lines of the readme since the beginning.

Besides this when I forked the project it had a different licensing: 
 License
 You can do whatever you like with this design.

I think I played fair
best regards
Marco
